// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZc8lAZiKA8446OQkkAkYRFFwZjW_8K6g',
    appId: '1:244039563257:web:ab34f0e9b12f21eb34af28',
    messagingSenderId: '244039563257',
    projectId: 'notesapp-5cb78',
    authDomain: 'notesapp-5cb78.firebaseapp.com',
    storageBucket: 'notesapp-5cb78.firebasestorage.app',
    measurementId: 'G-BTSW6NLG90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl3QPwquPakyuSYY_EunzN2kkoVgAzT7M',
    appId: '1:244039563257:android:a23a496fa6f2452f34af28',
    messagingSenderId: '244039563257',
    projectId: 'notesapp-5cb78',
    storageBucket: 'notesapp-5cb78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAp8jQb0-7Jql5NkqAuQLAQDLmFktDmyg',
    appId: '1:244039563257:ios:c20aa1bcf4341daf34af28',
    messagingSenderId: '244039563257',
    projectId: 'notesapp-5cb78',
    storageBucket: 'notesapp-5cb78.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAp8jQb0-7Jql5NkqAuQLAQDLmFktDmyg',
    appId: '1:244039563257:ios:c20aa1bcf4341daf34af28',
    messagingSenderId: '244039563257',
    projectId: 'notesapp-5cb78',
    storageBucket: 'notesapp-5cb78.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZc8lAZiKA8446OQkkAkYRFFwZjW_8K6g',
    appId: '1:244039563257:web:bae3e8b6f02c855034af28',
    messagingSenderId: '244039563257',
    projectId: 'notesapp-5cb78',
    authDomain: 'notesapp-5cb78.firebaseapp.com',
    storageBucket: 'notesapp-5cb78.firebasestorage.app',
    measurementId: 'G-HNDB7FYQXX',
  );
}
